<Project>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <NeutralLanguage>es-CR</NeutralLanguage>
    <Authors>Ivannia Porras Miranda; Anyelina Chacón Mora</Authors>
    <Product>Sistema de Gestión de Licitaciones</Product>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
